CREATE TABLE tasks (
    id BIGINT NOT NULL,
    description VARCHAR(100) NOT NULL,
    isActive SMALLINT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);