CREATE TABLE tasks (
    id BIGINT NOT NULL auto_increment,
    description VARCHAR(100) NOT NULL,
    active SMALLINT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);